config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "groups#index"
  resources :groups, only: [:new, :create, :show] do
    resources :documents, only: [:index, :create, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
  belongs_to :group
  has_one_attached :pdf

  with_options presence: true do
  validates :document_title
  validates :description
  validates :pdf
  end

end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :documents

  validates :group_name,     presence: true
  validates :image,          presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :last_name, :first_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: 'は全角で入力してください' }
    validates :last_name_kana, :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: 'は全角カタカナで入力してください' }
    validates :password,
            format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'は半角英数字混合での入力してください' }
  end

  has_many :groups
  has_many :messages
  has_many :documents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'sample' && password == '1234'
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:last_name, :first_name, :last_name_kana, :first_name_kana])
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  
  def index
    @documents = Document.all
  end

  def new
    @document = Document.new
  end
  
  def create
    @group = Group.find(params[:group_id])
    @document = @group.documents.new(document_params)
    if @document.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    respond_to do |format|
      format.pdf do
        send_file(@pdf, filename: 'document_title', type: 'application/pdf', disposition: :inline)
      end
    end
  end

  private 
  
  def document_params
    params.require(:document).permit(:document_title, :description, :pdf).merge(user_id: current_user.id)
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @group = Group.find(params[:id])
    @document = Document.new
    @documents = @group.documents.includes(:user)
  end

  private

  def group_params
    params.require(:group).permit(:group_name, :image).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/documents/_document.html.erb
<ul class = "group-lists">
  <% @documents.each do |document| %>
    <li class='list'>
      <% if document.pdf.representable? %>
        <%= link_to image_tag document.pdf.preview(resize: '300x300'), class: 'document_list' %>
        <div class="document_name">
          <p><%= document.document_title %></p>
        </div>
    <% end %>
    </li>
  <% end %>
</ul>

app/views/documents/new.html.erb
<%
=begin
%>
<div class="group-wrapper">
  <div class="page-heading">
    <h2>資料アップロード</h2>
  </div>
</div>
<div class="group-wrapper">
  <div class="group-content">
    <%= form_with model: @document, local: true do |f| %>
      <div class="field-login">
        <%= "資料タイトル" %><br />
        <%= f.text_area :document_title, class:"document-text", id:"document-name" %>
      </div>
      <div class="field-login">
        <%= "資料説明" %><br />
        <%= f.text_area :description, class:"description-text", id:"description-name" %>
      </div>

      <div class="field-login">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :pdf, id:"group-image" %>
      </div>

      <div class="actions">
        <%= f.submit "アップロードする", class: "group-btn" %>
      </div>
    <% end %>
  </div>
</div>

<%
=end
%>

app/views/groups/_header.html.erb
<header>
    <div class='logo'>
      <%= link_to 'DoCollect', root_path %>
    </div>
    <div class='status'>
      <% if user_signed_in? %>
        <div class="user_nav grid-6">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        </div>
      <% end %>
    </div>
  </div>
</header>

app/views/groups/index.html.erb
<div class="group-btn-wrapper">
  <div class="group-btn">
    <%= link_to "グループを作成する", new_group_path %>
  </div>
</div>

<ul class="group-lists">
  <% @groups.each do |group| %>
    <li class='list'>
      <%= link_to group_path(group.id), get: :method, class: "group-list" do %>
        <%= image_tag(group.image, class: 'group-image') %>
        <div class="group-name">
          <p><%= group.group_name %></p>
        </div>
        <div class="arrow-btn">
          <h2>"＞"</h2>
        </div>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/groups/new.html.erb
<div class="group-wrapper">
  <div class="page-heading">
    <h2>新規グループ作成</h2>
  </div>
</div>
<div class="group-wrapper">
  <div class="group-content">
    <%= form_with model: @group, local: true do |f|%>
      <div class="field-login">
        <%= "グループ名" %><br />
        <%= f.text_area :group_name, class:"group-text", id:"group-name" %>
      </div>

      <div class="field-login">
        <p>
          クリックして画像をアップロード
        </p>
        <%= f.file_field :image, id:"group-image" %>
      </div>

      <div class="actions">
        <%= f.submit "作成する", class: "group-btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<div class="document-btn-wrapper">
  <div class="upload-btn">
    <%= form_with model: [@group, @document], local: true do |f| %>
      <div class="field-title">
        <%= "資料タイトル" %>
        <%= f.text_area :document_title, class:"document-text", id:"document-name" %>
      </div>
      <div class="field-login">
        <%= "資料説明" %>
        <%= f.text_area :description, class:"description-text", id:"description-name" %>
      </div>
      <div class="document-file">
          <%= f.file_field :pdf, id:"document-file" %>
      </div>
      <div class="actions">
        <%= f.submit "アップロードする", class: "group-btn" %>
      </div>
    <% end %>
  </div>
</div>



        <%# // ログインしているユーザーには上記を表示する %>
          <%# 投稿に紐づくコメントを一覧する処理を記述する %>

<div class="user__card">
  <%= render partial: "documents/document", collection: @group.documents %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Docollect</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&family=Open+Sans:wght@300&family=Raleway:wght@100;500&display=swap" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <% if user_signed_in? %>
    <header>
      <div class='logo'>
        <%= link_to 'DoCollect', root_path %>
      </div>
      <div class='status'>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          </div>
        <% end %>
      </div>
    </div>
    </header>
  <% end %>

    <%= yield %>
  </body>
</html>